import "./global.css";

export const metadata = {
  title: "Welcome to sandbox",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0&icon_names=favorite"
      />
      <script src="https://unpkg.com/react-scan/dist/auto.global.js" async />
      <body className="bg-white dark:bg-secondary-950 text-black dark:text-white">
        {children}
      </body>
    </html>
  );
}
