import "./global.css";

export const metadata = {
  title: "Welcome to sandbox",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <script src="https://unpkg.com/react-scan/dist/auto.global.js" async />
      <body>{children}</body>
    </html>
  );
}
